# Lab 3
## NumPy Practice Lab

This lab is designed to give you practice with using the NumPy module in Python. This lab is worth 10 points. For all these problems, make sure you print your output so it appears beneathe the appropriate cell when run. Submit a .ipynb file by Monday, Sept. 13, 2021 at 11:59pm on BlackBoard.

## David Proksch proks1dl
## ITC510 - Fall 2021

In [3]:
pip install numpy >> /dev/null

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

### 1. In the code cell below, write a Python script to create an array with values ranging from 21 to 36. (2 points)

Example output:

    [21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36]

In [19]:
a = np.arange(21,37, step=1)
print(a)

[21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36]


### 2. In the code cell below, write a Python script to create a 3x3 matrix with values ranging from 2 to 10. (2 points)

Example output:

    [[ 2  3  4]                                                             
     [ 5  6  7]                                                             
     [ 8  9 10]]


In [13]:
m=np.matrix(range(2,11)).reshape(3,3)
print(m)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


### 3. In the code cell below, write a Python script to reverse the order of the array created from exercise 1. (2 points)
    
Example output:

    [36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21]

In [23]:
o=np.sort(a)[::-1]
print(o)

[36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21]


### 4.  In the code cell below, to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array. Format the output to have at most 2 significant digits displayed. (2 points)

Example input:

    [0, 12, 45.21 ,34, 99.91]
    
Example output:

    [-17.78 -11.11 7.34 1.11 37.73]

In [11]:
c=np.array([0, 12, 45.21, 34, 99.91])

def c2f(d):
    return (((d* (9/5))) + 32)            


            
f=c2f(c)
print(f)

[ 32.     53.6   113.378  93.2   211.838]


### 5. In the code cell below, write a Python script to remove nan values from a given array. (2 points)

Example input:

    [120. 240. nan nan nan 800. 980.]
    
Example output:

    [120. 240. 800. 980.]

In [14]:
a = np.array([120., 240., np.nan, np.nan, np.nan, 800., 980.])

print(a[~ np.isnan(a)])

[120. 240. 800. 980.]
